### PR TITLE
completed dom-manipulation

### PR DESCRIPTION
**Pull request by Quintin-Russell**
image

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Good job on the click count, now make sure you do the button color updates!

**Comment by Quintin-Russell** [comment]
it does, just checked

**Comment by Quintin-Russell** [comment]
image

**Comment by Quintin-Russell** [comment]
image

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
